### ISSUE TITLE
Scroll Bars on pop-up.

### ISSUE THREAD

**Issue by Zoltu** [keithamus/LinkyPass#21]
![image](https://f.cloud.github.com/assets/886059/1588008/4288cdb6-5247-11e3-806a-d25d91a40c37.png)

I just installed LinkyPass (yay for getting back into the store!) and the first click of the pop-up looked like the above, with scroll bars.  I am on Windows 8.1, Google Chrome 31.0.1650.57.

Also, when I scroll the globe doesn't scroll with the rest of the window:
![image](https://f.cloud.github.com/assets/886059/1588018/7eba4666-5247-11e3-8015-1d96a8180a95.png)

**Comment by dswd** [comment]
I tried removing those lines and it worked without the reported problems. Chrome might have fixed that issue in the meantime.
